[programs.localnet]
race_staking_program = "AzUUwhQYdscAAcuJ2182k99ZzUbpogr2QD5fusMbERhn"
race_nft_staking_program = "13M2mV5VmUx9KtaapArUmiBbSDF1PZKdqW3fneoFBZqV"

[programs.devnet]
race_staking_program = "AzUUwhQYdscAAcuJ2182k99ZzUbpogr2QD5fusMbERhn"
race_nft_staking_program = "13M2mV5VmUx9KtaapArUmiBbSDF1PZKdqW3fneoFBZqV"

[programs.mainnet]
race_staking_program = "AzUUwhQYdscAAcuJ2182k99ZzUbpogr2QD5fusMbERhn"
race_nft_staking_program = "13M2mV5VmUx9KtaapArUmiBbSDF1PZKdqW3fneoFBZqV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
#cluster = "http://127.0.0.1:8899"
#wallet = "/home/gitpod/.config/solana/id.json"
wallet = "/kg/solana/my_keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
